config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: :signout
  get 'login', to: 'sessions#login', as: :login
  get 'dashboard', to: 'users#dashboard', as: :dashboard

  get 'users/search_by_email', to: 'users#search_by_email'
  get 'devices/sdks', to: 'devices#sdks'
  get 'devices/help', to: 'devices#help'
  # get 'devices/dummy', to: 'devices#dummy'
  resources :users, except: [:new, :create]

  resources :roles, except: [:new, :show]
  # resources  :networks, except: [:show] do
  #   put 'add_device'
  #   put 'remove_device'
  # end
  resources  :devices, except: [:new, :edit] do
    get 'script'
    put 'toggle'
    put 'add_user'
    put 'remove_user'
    # put 'add_network'
  end

  root to: "users#dashboard"
end

app/models/device.rb
class Device < ActiveRecord::Base
  acts_as_paranoid
  has_paper_trail

  # belongs_to :network
  has_one :devices_owner, -> { where(role: :owner) }, class_name: 'DevicesUser', dependent: :destroy
  has_one :owner, through: :devices_owner, source: :user
  has_many :devices_users, -> { where(role: :shared_user) }, class_name: 'DevicesUser', dependent: :destroy
  has_many :shared_users, through: :devices_users, source: :user
  has_one :aws_thing, dependent: :destroy

  enum status: {
    on: 'on',
    off: 'off'
  }

  enum owner_status: {
    active: 'active',
    inactive: 'inactive'
  }

  before_validation :init
  after_create :create_aws_linkage
  validates_presence_of :serial_number, :name, :status, :slug, :owner_status
  validates_uniqueness_of :slug, :serial_number


  def init
    self.status ||= 'off'
    self.owner_status ||= 'active'
    self.serial_number ||= StringGenerator.device_serial_number
    self.slug ||= StringGenerator.slug_for_device
  end

  def to_param
    slug
  end

  def create_aws_linkage
    DeviceManager.new(self).create_aws_linkage
  end

  def toggle
    statuses = self.class.statuses.keys
    current_index = statuses.index(self.status)
    current_index = (current_index + 1) % statuses.count
    self.public_send("#{statuses[current_index]}!")
  end

  def self.find(input)
    input.to_i == 0 ? find_by_slug(input) : super
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  before_action :set_device, only: [:destroy, :toggle]
  before_action :set_owned_device, only: [:edit, :update, :add_user, :remove_user,
                                          :script, :show, :add_network]

  def index
    @devices = filtered_devices
    render_response(data: {
      devices: @devices
    })
  end

  def help
    param! :category, String, required: true, blank: false, in: %w(node embedded_c python procedure)
    render "devices/connectivity/#{params[:category]}"
  end

  # def dummy
  # end

  # def new
  #   @device = Device.new
  # end

  # def add_network
  #   param! :network_id, String, required: true, blank: false
  #   @owned_device.update(network: Network.find(params[:network_id]))
  #   flash[:success] = 'Successfully Added Network'
  #   redirect_to devices_path(category: :owned)
  # end

  def create
    device = current_user.owned_devices.create!(params_attributes)
    flash[:success] = 'Successfully created device'
    render_response(
      redirect_path: devices_path(category: :owned)
    )
  end

  def update
    @owned_device.update_attributes!(params_attributes)
    flash[:success] = 'Successfully updated device'
    render_response(
      redirect_path: devices_path(category: :owned)
    )
  end

  def destroy
    device_manager.remove_user(current_user)
    flash[:success] = 'Success removed device'
    render_response(
      redirect_path: devices_path(category: :owned)
    )
  end

  def toggle
    param! :state, String, in: %w(on off)
    device_manager.toggle
    render_response
  end

  def add_user
    param! :email, String, required: true, blank: false
    user = User.find_by_email!(params[:email])
    owned_device_manager.add_user(user)
    flash[:success] = 'Successfully added user'
    render_response(
      redirect_path: device_path(@owned_device)
    )
  end

  def remove_user
    param! :email, String, required: true, blank: false
    user = User.find_by_email!(params[:email])
    owned_device_manager.remove_user(user)
    flash[:success] = 'Successfully removed user'
    render_response(
      redirect_path: device_path(@owned_device)
    )
  end

  def script
    data = owned_device_manager.generate_credentails_file
    send_file File.join(Rails.root, 'public', 'temp_device_credentials', 'certs.zip')
  end

  def sdks
    param! :platform, String, required: true, blank: false, in: %w(embedded_c nodejs python)
    send_file File.join(Rails.root, 'public', 'device-sdks', "#{params[:platform]}.zip")
  end

  private

  def owned_devices
    current_user.owned_devices
  end

  def shared_devices
    current_user.shared_devices
  end

  def joined_errors(object)
    object.errors.messages.map { |key, value| key.to_s + ' ' + value.join(', ') }.join(', ')
  end

  def set_owned_device
    @owned_device ||= current_user.owned_devices.find_by_slug!(params[:device_id] || params[:id])
  end

  def set_shared_device
    @shared_device ||= current_user.shared_devices.find_by_slug!(params[:device_id] || params[:id])
  end

  def set_device
    @device ||= current_user.devices.find_by_slug!(params[:device_id] || params[:id])
  end

  def params_attributes
    params.require(:device).permit(:name)
  end

  def device_manager
    @device_manager ||= DeviceManager.new(@device)
  end

  def owned_device_manager
    @owned_device_manager ||= DeviceManager.new(@owned_device)
  end

  def filtered_devices
    if params[:category].present?
      case params[:category]
      when 'shared'
        shared_devices
      when 'owned'
        owned_devices
      else
        current_user.devices
      end
    else
      current_user.devices
    end
  end
end

app/views/devices/_control_device.html.erb
<div class="col-md-4 col-sm-4 col-xs-12 profile_details">
  <div class="well profile_view">

    <div class="col-sm-12">
      <h2><%= h truncate(control_device.name, length: 30) %></h2>
      <div class="left col-xs-7">
        <h2></h2>
      </div>
      <div class="right col-xs-5 text-center">
      </div>
    </div>
    <div class="col-xs-12 bottom text-center">
      <div class="col-xs-12">
        <span style="float: right;">
          <%= check_box_tag :state, 'on', control_device.on?, class: 'js-switch', data: { switchery: 'true', device_slug: control_device.slug } %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/devices/_owned_device.html.erb
<div class="col-md-4 col-sm-4 col-xs-12 profile_details">
  <div class="well profile_view">

    <div class="col-sm-12">
      <button type="button" class="btn btn-link" data-toggle="modal" data-target=".bs-example-modal-sm-<%= owned_device.slug %>" style="width: 100%"><%= h truncate(owned_device.name, length: 30) %></button>
      <div class="modal fade bs-example-modal-sm-<%= owned_device.slug %>" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <%= form_for owned_device do |f| %>
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel2">Update Name</h4>
              </div>
              <div class="modal-body">
                <p>
                  <div class="clearfix"></div>
                  <%= f.text_field :name, class: 'form-control' %>
                </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <input type="submit" class="btn btn-primary" value="Update">
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="left col-sm-12">
        <h2>Serial No: <%= owned_device.serial_number %></h2>
      </div>
      <!-- <div class="left col-sm-12">
      <%# if owned_device.network.present? %>
        <h2>Network: <%#= link_to(h(truncate(owned_device.network.name, length: 30)), edit_network_path(owned_device.network)) %></h2>
      <%# else %>
        <h2>Network: <button type="button" class="btn btn-link" data-toggle="modal" data-target=".bs-example-modal-sm-<%= owned_device.slug %>-network">Add Network</button></h2>
        <div class="modal fade bs-example-modal-sm-<%#= owned_device.slug %>-network" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <%#= form_tag device_add_network_path(owned_device), method: :put do %>
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel2">Select Network</h4>
                </div>
                <div class="modal-body">
                  <p>
                    <div class="clearfix"></div>
                    <select name="network_id" class="form-control">
                      <%#= options_from_collection_for_select(@current_user.networks, :slug, :name) %>
                    </select>
                  </p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <input type="submit" class="btn btn-primary" value="Attach">
                </div>
              <%# end %>
            </div>
          </div>
        </div>
      <%# end %>

      </div> -->
      <div class="left col-xs-7">
        <h2></h2>
      </div>
      <div class="right col-xs-5 text-center">
      </div>
    </div>
    <div class="col-xs-12 bottom text-center">
      <div class="col-xs-12">
        <%= link_to device_path(owned_device), style: 'float: left;', class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "All shared user will also lose control over the owned_device. Do you still want to delete?"} do %>
          <i class="fa fa-remove"></i> Delete
        <% end %>
        <%= link_to device_path(owned_device), style: 'float: left;', class: 'btn btn-info btn-xs' do %>
          <i class="fa fa-user"></i> Shared Users
        <% end %>
        <%# if owned_device.network.present? %>
          <%= link_to device_script_path(owned_device), style: 'float: left;', class: 'btn btn-dark btn-xs' do %>
            <i class="fa fa-download"></i> Credentials
          <% end %>
        <%# end %>
      </div>
    </div>
  </div>
</div>

app/views/devices/_shared_device.html.erb
<div class="col-md-4 col-sm-4 col-xs-12 profile_details">
  <div class="well profile_view">
    <div class="col-sm-12">
      <h2><%= h truncate(shared_device.name, length: 30) %></h2>
      <div class="left col-xs-7">
        <h2></h2>
      </div>
      <div class="right col-xs-5 text-center">
      </div>
    </div>
    <div class="col-xs-12 bottom text-center">
      <div class="col-xs-12">
        <%= link_to device_path(shared_device), style: 'float: left;', class: 'btn btn-danger btn-xs', method: :delete, data: {confirm: "Are You Sure?"} do %>
          <i class="fa fa-remove"></i> Delete
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/devices/_user.html.erb
<div class="col-md-4 col-sm-4 col-xs-12 profile_details">
  <div class="well profile_view">
    <div class="col-sm-12">
      <h4 class="brief"><i><%= user.name %></i></h4>
      <div class="left col-xs-7">
        <p><%= user.email %></p>
      </div>
      <div class="right col-xs-5 text-center">
        <%= image_tag user.photo(:small), class: 'img-circle img-responsive', style: 'float: right;' %>
      </div>
       <div class="left col-xs-7">
        <h2></h2>
      </div>
    </div>
    <div class="col-xs-12 bottom text-center">
      <div class="col-xs-12 col-sm-6 emphasis">
      </div>
      <div class="col-xs-12 col-sm-6 emphasis">
        <%= link_to device_remove_user_path(device, { email: user.email }), style: 'float: right;', class: 'btn btn-danger btn-xs', method: :put, data: { confirm: "Are You Sure?" } do %>
            <i class="fa fa-remove"></i> Remove
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/devices/index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Devices</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
            <h2>All Devices</h2>
            <ul class="nav navbar-right panel_toolbox">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Add New Device</button>
              <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">
                    <%= form_for :device do |f| %>
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel2">Enter Name</h4>
                      </div>
                      <div class="modal-body">
                        <p>
                          <div class="clearfix"></div>
                          <%= f.text_field :name, class: 'form-control' %>
                        </p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" value="Add">
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <% if params[:category] == 'shared' %>
              <%= render partial: 'shared_device', collection: @devices %>
            <% elsif params[:category] == 'owned' %>
              <%= render partial: 'owned_device', collection: @devices %>
            <% else %>
              <%= render partial: 'control_device', collection: @devices %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/devices/show.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Devices</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
            <h2>Share</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="col-md-6 col-md-offset-3">
              <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel">
                  <label>Add User: </label>
                  <div class="input-group">
                    <input type="email" class="form-control" id="email" placeholder="User's Email you wants to share with..">
                    <span class="input-group-btn">
                      <button type="button" class="btn btn-primary collapsed" role="tab" id="headingTwo" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false"  aria-controls="collapseTwo" data-slug="<%= @owned_device.slug %>">Search!</button>
                    </span>
                  </div>
                  <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false" style="height: 0px;">
                    <div class="panel-body">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="x_title">
            <h2>Shared Users</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <%= render partial: 'user', collection: @owned_device.shared_users, locals: { device: @owned_device } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $("#headingTwo").on("click", function (event) {
    var slug = $('button#headingTwo').data('slug');
    if($('button.collapsed').length) {
      var email = $('#email').val();
      if(email.match(/^.+@[a-zA-Z]+\.\w+$/)) {
        $.ajax({
          url: "/users/search_by_email",
          type: "GET",
          data: { email: email, device_slug: slug },
          dataType: "SCRIPT"
        });
      } else {
        alert('Please Enter a valid email address:');
        return false;
      }
    }
  });
</script>

<style>
  .accordion .panel:hover {
    background: #fff;
  }
  .accordion .panel {
    margin-bottom: 5px;
    border-radius: 0;
  }
</style>