config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: :signout
  get 'login', to: 'sessions#login', as: :login
  get 'dashboard', to: 'users#dashboard', as: :dashboard

  get 'users/search_by_email', to: 'users#search_by_email'
  get 'devices/sdks', to: 'devices#sdks'
  get 'devices/help', to: 'devices#help'
  # get 'devices/dummy', to: 'devices#dummy'
  resources :users, except: [:new, :create]

  resources :roles, except: [:new, :show]
  # resources  :networks, except: [:show] do
  #   put 'add_device'
  #   put 'remove_device'
  # end
  resources  :devices, except: [:new, :edit] do
    get 'script'
    put 'toggle'
    put 'add_user'
    put 'remove_user'
    # put 'add_network'
  end

  root to: "users#dashboard"
end

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    User Device Control Panel by <a href="https://aotnext.com">AOT Next</a>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <!-- <div class="navbar nav_title" style="border: 0;">
        <%= link_to root_path, class: "site_title" do %>
          <span><%= image_tag 'logo.png' %></span>
        <% end %> -->
      <div class="navbar nav_title">
        <%= link_to root_path, class: 'site_title', style: 'padding: 8px;' do %>
          <%= image_tag 'favicon.ico', style: 'margin-right: -6px;' %>
          <span><%= image_tag 'white-logo1.png' %></span>
        <% end %>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag current_user.photo(:small), :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <h2><%= link_to current_user.name, user_path(current_user), class: 'btn btn-success' %></h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br/>

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section">
          <div class="clearfix"></div>
          <ul class="nav side-menu">
            <% if current_user.admin? %>
              <li><a><i class="fa fa-adn"></i> Admin Panel <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu" style="display: none">
                  <li><%= link_to 'Users', users_path %>
                  </li>
                  <li><%= link_to 'Roles', roles_path %>
                  </li>
                </ul>
              </li>
            <% end %>
            <!-- <li><a><i class="fa fa-bolt"></i> Networks <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><%#= link_to 'Add New Network', new_network_path %>
                </li>
                <li><%#= link_to 'My Networks', networks_path %>
                </li>
              </ul>
            </li> -->
            <li><a><i class="fa fa-cogs"></i> Devices <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><%= link_to 'Control Panel', devices_path(category: :all) %>
                </li>
                <li><%= link_to 'Owned Devices', devices_path(category: :owned) %>
                </li>
                <li><%= link_to 'Shared Devices', devices_path(category: :shared) %>
                </li>
              </ul>
            </li>
            <li class=""><a><i class="fa fa-sitemap"></i> Help <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none;">
                <li><a>Device Connectivity<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu" style="">
                    <li><%= link_to 'Procedure', devices_help_path(category: :procedure) %>
                    </li>
                    <li><%= link_to 'Node Js', devices_help_path(category: :node) %>
                    </li>
                    <li><%= link_to 'Embedded C', devices_help_path(category: :embedded_c) %>
                    </li>
                    <li><%= link_to 'Python', devices_help_path(category: :python) %>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/partials/_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">

  <div class="nav_menu">
    <nav class="" role="navigation">
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag current_user.photo(:small) %><%= current_user.name.titleize %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li>
              <%= link_to signout_path do %>
                <i class="fa fa-sign-out pull-right"></i> Log Out
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>

</div>
<!-- /top navigation -->