config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: :signout
  get 'login', to: 'sessions#login', as: :login
  get 'dashboard', to: 'users#dashboard', as: :dashboard

  get 'users/search_by_email', to: 'users#search_by_email'
  get 'devices/sdks', to: 'devices#sdks'
  get 'devices/help', to: 'devices#help'
  # get 'devices/dummy', to: 'devices#dummy'
  resources :users, except: [:new, :create]

  resources :roles, except: [:new, :show]
  # resources  :networks, except: [:show] do
  #   put 'add_device'
  #   put 'remove_device'
  # end
  resources  :devices, except: [:new, :edit] do
    get 'script'
    put 'toggle'
    put 'add_user'
    put 'remove_user'
    # put 'add_network'
  end

  root to: "users#dashboard"
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_paranoid
  has_paper_trail

  has_many :devices_users, -> { where(role: :shared_user) }, class_name: 'DevicesUser', dependent: :destroy
  has_many :shared_devices, through: :devices_users, source: :device
  has_many :devices_owners, -> { where(role: :owner) }, class_name: 'DevicesUser', dependent: :destroy
  has_many :owned_devices, through: :devices_owners, source: :device

  has_many :permissions, through: :roles
  # has_many :networks, dependent: :destroy
  has_and_belongs_to_many :roles
  has_attached_file :photo, styles: { small: "50x50", medium: "200x200"},
                      path: "/public/:env/:attachment/:id/:style/:updated_at"

  validates_presence_of :name, :slug, :email, :uid
  validates_uniqueness_of :slug, :email, :uid
  validates_attachment :photo, content_type: { content_type: /\Aimage\/.*\Z/ }

  before_validation :init

  def init
    self.slug ||= StringGenerator.slug_for_user
  end

  def to_param
    slug
  end

  def shared_users
    user_ids = owned_devices.map { |device| device.shared_user_ids }.flatten
    self.class.where(id: user_ids)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.photo = open(auth.info.image)
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
      user.roles.push(Role.normal) unless user.normal?
    end
  end

  def devices
    Device.where(id: device_ids)
  end

  def device_ids
    (shared_device_ids + owned_device_ids).uniq
  end

  def admin?
    roles.admin.present?
  end

  def normal?
    roles.normal.present?
  end

  def permitted?(controller, action)
    permission = Permission.where(controller: controller, action: action).first
    permission.open? || permission_ids.include?(permission.id) if permission
  end

  def self.find(input)
    input.to_i == 0 ? find_by_slug(input) : super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :destroy, :update]

  def index
    @users = User.all
  end

  def edit
  end

  def update
    @user.update_attributes!(params_attributes)
    flash[:success] = 'Successfully Updated User'
    redirect_to :back
  end

  def destroy
    @user.destroy!
    flash[:success] = 'Successfully Destroyed User'
    redirect_to :back
  end

  def dashboard
    @owned_devices = current_user.owned_devices
    @shared_devices = current_user.shared_devices
    # @networks = current_user.networks
    @shared_users = current_user.shared_users
    @all_devices = current_user.devices
    render_response(data: {
      owned_devices: @owned_devices,
      shared_devices: @shared_devices,
      shared_users: @shared_users,
      all_devices: @all_devices
    })
  end

  def search_by_email
    param! :email, String, required: true, blank: false
    param! :device_slug, String, required: true, blank: false
    @user = User.find_by_email!(params[:email])
    @device = current_user.devices.find_by_slug!(params[:device_slug])
    @already_user = @user.devices.pluck(:id).include?(@device.id)
    render_response(data: {
      device: @device,
      user: @user,
      already_user: @already_user
    })
  end

  private

  def user_manager
    @user_manager ||= UserManager.new(current_user)
  end

  def params_attributes
    if current_user.admin?
      params.require(:user).permit(:name, :photo, role_ids: [])
    else
      params.require(:user).permit(:name, :photo)
    end
  end

  def set_user
    if current_user.admin?
      @user ||= User.find_by_slug!(params[:device_id] || params[:id])
    else
      @user ||= current_user
    end
  end
end

app/views/users/_device.html.erb
<tr class="even pointer">
  <td><%= device.name %></td>
  <td><%= device.created_at %></td>
</tr>

app/views/users/_user.html.erb
<tr class="even pointer">
  <td><%= user.name %></td>
  <td><%= user.provider %></td>
  <td><%= user.email %></td>
  <td><%= user.created_at %></td>
  <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-info' %>
    <%= link_to 'Delete', user_path(user), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } if user.id != current_user.id %>
  </td>
</tr>

app/views/users/dashboard.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User Dashboard</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_title">
          <h2>Summary</h2>
            <div class="clearfix"></div>
          </div>
          <div>
            <div class="x_content">
              <%= link_to devices_path(category: :owned) do %>
                <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-credit-card"></i>
                    </div>
                    <div class="count"><%= @owned_devices.count %></div>

                    <h3>Owned <%= 'Device'.pluralize(@owned_devices.count) %></h3>
                  </div>
                </div>
              <% end %>

              <%= link_to devices_help_path(category: :procedure) do %>
                <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-line-chart"></i>
                    </div>
                    <div class="count">Procedure</div>

                    <h3>To connect your device</h3>
                  </div>
                </div>
              <% end %>

              <%= link_to devices_path(category: :all) do %>
                <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-check-square"></i>
                    </div>
                    <div class="count"><%= @all_devices.count %></div>

                    <h3><%= 'Device'.pluralize(@all_devices.count) %> under control</h3>
                  </div>
                </div>
              <% end %>

              <%#= link_to networks_path do %>
                <!-- <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-wifi"></i>
                    </div>
                    <div class="count"><%#= @networks.count %></div>

                      <h3><%#= 'Network'.pluralize(@networks.count) %></h3>
                  </div>
                </div> -->
              <%# end %>

              <%= link_to devices_help_path(category: :node) do %>
                <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-book"></i>
                    </div>
                    <div class="count">Node Js</div>

                    <h3>Connect with Node Js Client</h3>
                  </div>
                </div>
              <% end %>

              <%= link_to devices_path(category: :shared) do %>
                <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-code-fork"></i>
                    </div>
                    <div class="count"><%= @shared_devices.count %></div>

                    <h3>Shared <%= 'Device'.pluralize(@shared_devices.count) %></h3>
                  </div>
                </div>
              <% end %>

              <%= link_to devices_help_path(category: :python) do %>
                <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-book"></i>
                    </div>
                    <div class="count">Python</div>

                    <h3>Connect with Python Client</h3>
                  </div>
                </div>
              <% end %>

              <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-group"></i>
                  </div>
                  <div class="count"><%= @shared_users.count %></div>

                  <h3>Shared <%= 'User'.pluralize(@shared_users.count) %></h3>
                </div>
              </div>

              <%= link_to devices_help_path(category: :embedded_c) do %>
                <div class="animated flipInY col-lg-6 col-md-6 col-sm-12 col-xs-12">
                  <div class="tile-stats">
                    <div class="icon"><i class="fa fa-book"></i>
                    </div>
                    <div class="count">Embedded C</div>

                    <h3>Connect with Embedded C Client</h3>
                  </div>
                </div>
              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Users</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
            <h2><%= @user.name.titleize %></h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <%= form_for @user, html: { class: 'form-horizontal form-label-left' } do |f| %>
              <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Roles<span class="required"></span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.select :role_ids, options_for_select(Role.all.map {|role| [role.label, role.id]}, @user.role_ids), {}, class: 'tags-multi-select', multiple: true, style: 'width: 100%' %>
                </div>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <button type="submit" class="btn btn-success">Update</button>
              </div>
            <% end %>
          </div>
          <div class="x_title">
            <h2>Devices</h2>
            <div class="clearfix"></div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Owned Devices</h2>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Added On</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render partial: 'device', collection: @user.owned_devices %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Shared Devices</h2>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Added On</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render partial: 'device', collection: @user.shared_devices %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/help.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Help Section</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
            <h2>Connectivity Procedure</h2>
            <div class="clearfix"></div>
          </div>
          <div>
            <div class="x_content"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Users</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
          <h2>List</h2>
            <div class="clearfix"></div>
          </div>
          <div>
            <div class="x_content">
              <div class="table-responsive">
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">Name </th>
                      <th class="column-title">Provider </th>
                      <th class="column-title">Email </th>
                      <th class="column-title">Added On </th>
                      <th class="column-title">Actions </th>
                    </tr>
                  </thead>

                  <tbody>
                    <%= render partial: 'user', collection: @users %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/search_by_email.js.erb
$('.panel-body').first().html('');

<% if @already_user %>
  $('.panel-body').first().append('<h1>This User has already access to this device</h1>');
<% else @user.present? %>
  $('.panel-body').first().append('<div class="thumbnail col-md-8 col-md-offset-2">' +
    '<div class="image view view-first">' +
      "<%= j image_tag @user.photo(:medium), style: 'width: 100%; display: block;' %>" +
      '<div class="mask">' +
        '<p><%= @user.name %></p>' +
        "<%= j(link_to('Share', device_add_user_path(@device, { email: @user.email }), method: :put, class: 'btn btn-primary')) %>" +
      '</div>' +
    '</div>' +
    '<div class="caption">' +
      '<p><%= @user.email %></p>' +
    '</div>' +
  '</div>');
<% end %>

$('#email').val('');

app/views/users/show.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User Profile</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="height:600px;">
          <div class="x_title">
            <h2>Take a Look!</h2>
            <div class="clearfix"></div>
          </div>
          <div>
            <div class="x_content">
              <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                <div class="profile_img">
                  <div id="crop-avatar">
                    <%= image_tag current_user.photo(:medium), class: 'img-responsive avatar-view', size: '200x200' %>
                  </div>
                  <%#= link_to edit_user_path(current_user), class: 'btn btn-success', style: 'width: 200px;' do %>
                    <!-- <i class="fa fa-edit m-right-xs"></i>Edit Profile</a> -->
                  <%# end %>
                </div>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2><%= current_user.name.titleize %></h2>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">

                  <div class="">
                    <ul class="to_do">
                      <li>
                        <%= current_user.email %>
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel">
                    <a class="panel-heading collapsed" role="tab" id="headingOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                      <h4 class="panel-title">Account ID</h4>
                    </a>
                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" aria-expanded="false" style="height: 0px;">
                      <div class="panel-body">
                      <h1><%= current_user.uid %></h1>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>