config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: :signout
  get 'login', to: 'sessions#login', as: :login
  get 'dashboard', to: 'users#dashboard', as: :dashboard

  get 'users/search_by_email', to: 'users#search_by_email'
  get 'devices/sdks', to: 'devices#sdks'
  get 'devices/help', to: 'devices#help'
  # get 'devices/dummy', to: 'devices#dummy'
  resources :users, except: [:new, :create]

  resources :roles, except: [:new, :show]
  # resources  :networks, except: [:show] do
  #   put 'add_device'
  #   put 'remove_device'
  # end
  resources  :devices, except: [:new, :edit] do
    get 'script'
    put 'toggle'
    put 'add_user'
    put 'remove_user'
    # put 'add_network'
  end

  root to: "users#dashboard"
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions

  validates_presence_of :label
  validates_uniqueness_of :label

  def self.admin
    find_by_label(:Admin)
  end

  def self.normal
    find_by_label(:Normal)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  before_action :set_role, only: [:edit, :update, :destroy]

  def create
    Role.create!(params_attributes)
    flash[:success] = 'Successfully Created Role'
    redirect_to roles_path
  end

  def new
    @role = Role.new
  end

  def update
    @role.update_attributes!(params_attributes)
    flash[:success] = 'Successfully Updated Role'
    redirect_to roles_path
  end

  def edit
  end

  def index
    @roles = Role.all
  end

  def destroy
    @role.destroy!
    flash[:success] = 'Successfully Deleted Role'
    redirect_to roles_path
  end

  private

  def params_attributes
    params.require(:role).permit(:label, permission_ids: [])
  end

  def set_role
    @role ||= Role.find(params[:id])
  end

end

app/views/roles/_form.html.erb
<%= form_for role, html: { class: 'form-horizontal form-label-left' } do |f| %>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="label">Label <span class="required">*</span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :label, class: 'form-control col-md-7 col-xs-12' %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Roles<span class="required"></span>
    </label>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.select :permission_ids, options_for_select(Permission.login.map {|permission| ["#{permission.controller}_#{permission.action}", permission.id]}, role.permission_ids), {}, class: 'tags-multi-select', multiple: true, style: 'width: 100%' %>
    </div>
  </div>
  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
    <button type="submit" class="btn btn-success">Update</button>
  </div>
<% end %>

app/views/roles/_role.html.erb
<tr class="even pointer">
  <td><%= role.label %></td>
  <td><%= link_to 'Edit', edit_role_path(role), class: 'btn btn-info' %>
    <%= link_to 'Delete', role_path(role), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/roles/edit.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User Roles</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
          <h2>Edit</h2>
            <div class="clearfix"></div>
          </div>
          <div>
            <div class="x_content">
              <%= render partial: 'form', locals: { role: @role } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/roles/index.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User Roles</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
          <h2>List</h2>
            <div class="clearfix"></div>
          </div>
          <div>
            <div class="x_content">
              <div class="table-responsive">
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">Name </th>
                      <th class="column-title">Actions </th>
                    </tr>
                  </thead>

                  <tbody>
                    <%= render partial: 'role', collection: @roles %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/roles/new.html.erb
<!-- page content -->
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>User Roles</h3>
      </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel" style="min-height:600px;">
          <div class="x_title">
          <h2>Add New</h2>
            <div class="clearfix"></div>
          </div>
          <div>
            <div class="x_content">
              <%= render partial: 'form', locals: { role: @role } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>